### PR TITLE
Fixed issue 59: ASN1 corrupted data exception on linux

### PR DESCRIPTION
**Pull request by Mrizzi-96**
#59

### CODE REVIEW

**Comment by DevTrevi** [comment]
Hi @Mrizzi-96 , thank you for reporting this issue.
I have better investigated what is causing the problem, and I found that the real bug is in the download method:

``` csharp
var content = await response.Content.ReadAsByteArrayAsync();
```

This method is not returning the byte array of the content of the base64 returned by the service, but instead is returning the byte array of the base64 string.
Even if your proposed fix will work with the italian trustlist provider, it will fail if used with another provider (i.e. the German trustlist provider)

I will fix the problem in next release with this code in `ItalianTrustListProvider.cs`:
``` csharp
var stringContent = await response.Content.ReadAsStringAsync();
var content = Convert.FromBase64String(stringContent);
```

I will then remove the previous fix:
``` csharp
// This will be replaced with the previous code below:
//var cert = new X509Certificate2(Convert.FromBase64String(Encoding.ASCII.GetString(certificateBytes)));
var cert = new X509Certificate2(certificateBytes);
```

Can you please give it a try in your environment before I release it? Thanks!

**Comment by Mrizzi-96** [comment]
Hi @DevTrevi,
This is a great solution! 
I tested it by creating a new branch based on your master, while also reverting the changes I've made in my previous pull request (#60). 
I can confirm that your solution works perfectly without my changes, so I look forward to its inclusion in your next release.
I attached the file diff here, so you can see exactly what I changed.
Let me know if you need anything else.
Cheers,
Marco.
[patch.txt](https://github.com/DevTrevi/DgcReader/files/7984474/patch.txt)

**Comment by Mrizzi-96** [comment]
Hi @DevTrevi,
While reviewing changes I got some unit test failures for ItalianTrustListProvider with the following exception:
```
  Message: 
Test method DgcReader.TrustListProviders.Italy.Test.ItalianTrustListProviderTests.TestConcurrency threw exception: 
System.AggregateException: One or more errors occurred. ---> Org.BouncyCastle.Security.Certificates.CertificateException: Failed to read certificate ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

  Stack Trace: 
Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
Convert.FromBase64String(String s)
PemParser.ReadPemObject(Stream inStream) line 81
X509CertificateParser.ReadPemCertificate(Stream inStream) line 72
X509CertificateParser.ReadCertificate(Stream inStream) line 152
--- End of inner exception stack trace ---
X509CertificateParser.ReadCertificate(Stream inStream) line 161
X509CertificateParser.ReadCertificate(Byte[] input) line 92
X509CertificatesUtils.GetCertificateData(String kid, Byte[] certificateBytes, ILogger logger) line 103
...etc
```
As far as I understand, we do not **always** need to convert the received certificate from base64, as you [suggested ](https://github.com/DevTrevi/DgcReader/pull/67#issuecomment-1027189720). We just need to do that when the application calls one of the X509Certificate2 constructors in the following methods.

```
 RuleValidators.Italy.CertificateExtendedKeyUsages.GetExtendedKeyUsages();
 TrustListProviders.Italy.X509CertificatesUtils.GetCertificateData();
```
In any other case, we do not need to do any conversion. 
My last fix passes all unit tests and works on Linux too.
Cheers,
Marco.

**Comment by DevTrevi** [comment]
Hi @Mrizzi-96, the failing tests are those targeting .NET Framework 4.5.2, because for that target I used Bouncy Castle and the previous fix that I suggested was incomplete (I have considered the .NET/.NET Framework > 4.7 targets only)

The previous solutions was the right one, but needs this additional change in the `AddPemHeaders` method:
``` csharp
//var decoded = Encoding.ASCII.GetString(certificateData); <-- Error
var decoded = Convert.ToBase64String(certificateData);
```

The issue with your solution is that other trustlist providers (German trustlist provider) stores the certificate in the right way, so if you register multiple trustlist providers and the certificate is returned by the German one, the code in ItalianRulesValidator will fail :)

**Comment by DevTrevi** [comment]
Thank you for your help! :)

**Pull request merged**
